{"name": "test_valid_login", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('driver', <FixtureRequest for <Function test_valid_login>>)", "trace": "file C:\\assignment\\mobile_ios\\tests\\test_login.py, line 12\n  def test_valid_login(driver):\nE       fixture 'driver' not found\n>       available fixtures: anyio_backend, anyio_backend_name, anyio_backend_options, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, free_tcp_port, free_tcp_port_factory, free_udp_port, free_udp_port_factory, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\assignment\\mobile_ios\\tests\\test_login.py:12"}, "description": "User can log in with valid credentials.", "start": 1758001833840, "stop": 1758001833840, "uuid": "ac400def-bd4d-4aa1-a09e-9c4aeaa8f30e", "historyId": "27b150db6705ef6511c7ecb21ff68d02", "testCaseId": "ab68c09e23714aa68c720c2ca07c0ecf", "fullName": "tests.test_login#test_valid_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DB-L-174"}, {"name": "thread", "value": "4640-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}